# Generated by Django 4.2.3 on 2023-10-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_season_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created_on']},
        ),
    ]
