# Generated by Django 4.2.3 on 2023-10-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_commentreplies_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentreplies',
            old_name='body',
            new_name='reply',
        ),
    ]
