# Generated by Django 4.2.3 on 2023-10-26 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_season_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentReplies',
            new_name='CommentReply',
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Comment Replies'},
        ),
    ]
