# Generated by Django 4.2.3 on 2023-10-26 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_commentreplies_commentreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='image',
            field=cloudinary.models.CloudinaryField(default='palceholder', max_length=255, verbose_name='image'),
        ),
    ]
