# Generated by Django 4.2.3 on 2023-11-02 22:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comment_approved_remove_commentreply_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('playlist_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=100)),
                ('external_url', models.URLField(max_length=100)),
                ('seasons', models.ManyToManyField(related_name='playlists', to='blog.season')),
            ],
        ),
    ]
