# Generated by Django 4.2.3 on 2023-11-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_spotifyplaylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyplaylist',
            name='seasons',
        ),
    ]
