# Generated by Django 4.2.3 on 2023-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_spotifyplaylist_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='blog.spotifyplaylist'),
        ),
    ]
