# Generated by Django 4.2.3 on 2023-11-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_season_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='playlists',
        ),
        migrations.AddField(
            model_name='spotifyplaylist',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='blog.season'),
        ),
    ]
