# Generated by Django 4.2.3 on 2023-11-03 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_season_playlists_spotifyplaylist_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='iframe_uri',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifyplaylist',
            name='image',
            field=models.URLField(),
        ),
    ]
