# Generated by Django 4.2.3 on 2023-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
