# Generated by Django 4.2.3 on 2023-11-14 14:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_commentreply_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='spotifyplaylist',
            options={'verbose_name_plural': 'Spotify Playlists'},
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
