# Generated by Django 4.2.3 on 2023-11-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_commentreply_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyplaylist',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
